### ISSUE TITLE
Promisfy the codebase

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#142]
Following the callback logic is pretty mind bending in some places. Promise support would eleviate much of this.

**Comment by kazk** [comment]
I've tried to use plain Promise, but it was still unclear :(
Node 7.6+ supports `async`/`await` and that helps significantly.
Also Node 8 will be released next month.
Using Node 8 should be a good choice because Node 8's LTS starts on `2017-10-01` and will be supported until `2019-12-31`.

---

I've been experimenting with multi-package approach and it's nice :) I'm currently using git tags to specify the version so it's not as flexible as it can be with package versioning, but I can improve the core runner without worrying about the language runners. As a demo, I made `go-runner` and `ruby-runner` using different versions of `runner`. Migrating to this approach shouldn't take long.

What are the requirements for the CI system you mentioned in #396?

**Comment by kazk** [comment]
@jhoffner here's a version of `lib/shovel.js` using `async`/`await` eliminating most of the nested callbacks and promises.

![image](https://cloud.githubusercontent.com/assets/639336/25549223/896e95b0-2c25-11e7-8b61-a92628d9d9b0.png)

kazk/codewars-runner@9f051a1d0e4c31edc1dd3618c3a8f70828483596

**Comment by jhoffner** [comment]
That code looks beautiful! 👍 👍 👍 

> I've been experimenting with multi-package approach and it's nice :)

Thats awesome. How much of an effort do you think it will be to convert the codebase? 

> What are the requirements for the CI system you mentioned in #396

I guess none possibly. Since the Docker files need to be built in order to be tested, everything is self contained already. All the CI does is call `make node`, `make ruby`, etc so as long as we still support that we should be good.

Hmm I just thought of something else we could do. It might be a good time to actually move the tests out of the docker file and just have them as a part of a build script. They sometimes leave artifacts behind that stay with the image forever. Its another one of those things that we did a long time ago when everything was one big hack and haven't really re-evaluated it since.

**Comment by kazk** [comment]
> How much of an effort do you think it will be to convert the codebase?

I think it depends on how we decide to do it.

Conversion itself is simple, just moving files around and `require` packages instead of relative paths.

I think it'll be easiest and cleanest to create `Codewars/codewars-runners` repository and convert runners one by one.
If this approach is ok, I can start experimenting further using Lerna and publishing temporary packages scoped under my account to see how it goes.
We can look into details like testing and CI there.

What do you think?

I need to think about how to proceed if we're doing this in-place.

**Comment by kazk** [comment]
FYI, I just converted `lua-runner` and took me around 25 minutes.

**Comment by kazk** [comment]
@jhoffner I made a `lua-runner` that is tested from outside (kazk/codewars-lua-runner@c70310a44a2f1b831415182716c39a021b2dea43). Every test case runs in independent container so cleaning up will be unnecessary.

I also noticed that [Travis](https://travis-ci.org/kazk/codewars-lua-runner/builds/227185176) has colored output now which makes scanning through the test cases easier for me.

![image](https://cloud.githubusercontent.com/assets/639336/25557653/add4ca5a-2cca-11e7-92ee-9c11726a267d.png)


Currently only `buffer.stdout` and `buffer.stderr` are testable. But I noticed there's `opts.format` that can be set to `json` after making this. I can use that and make the whole result buffer testable :)

I also made `buffer.stdout`/`buffer.stderr` to print if non-empty because sometimes it's useful to catch unwanted outputs. This can be turned off if cleaner test report is preferred.

**Comment by kazk** [comment]
Made the entire buffer testable.

- kazk/codewars-lua-runner@ac626f097859432788734da8a894098081cd0d3b
- <https://travis-ci.org/kazk/codewars-lua-runner/builds/227202660>

**Comment by jhoffner** [comment]
Great work @kazk. This new runner format you came up with is really coming together 👍

**Comment by kazk** [comment]
@jhoffner I'm going to experiment further and start playing with Lerna.
Hoping to have some POC within a week to help with discussing the details and deciding how we proceed with the conversion.

**Comment by kazk** [comment]
@jhoffner I have few questions.

How does `strategies.files()` ([lib/shovel.js#L111](https://github.com/Codewars/codewars-runner-cli/blob/05b31129d1a27e656224f51c9ffc8fe24a504234/lib/shovel.js#L111)) work? I found no tests and it doesn't take any arguments.
I'm guessing that this uses `opts` from the parent scope and provides some customized way to write files, like using manipulated paths.

---

How does `customStrategy(opts)` ([lib/shovel.js#L89](https://github.com/Codewars/codewars-runner-cli/blob/05b31129d1a27e656224f51c9ffc8fe24a504234/lib/shovel.js#L89)) work? I see that it provides the method `strategy.custom`, but it looks like it does more than that (`Object.assign(strategy, customStrategy(opts))`).

---

These are blocking because I'm thinking of using the following:


```javascript
// current
// exposing `opts` here like this is error-prone as seen with C++ issue fixed in #402
module.exports = function run(opts, cb) {
  shovel.start(opts, cb, {
    solutionOnly(runCode, fail) {
    },
    testIntegration(runCode, fail) {
    }
  });
};

// promisified
module.exports = createRunner({
  solutionOnly(opts) {
    return new Promise((resolve, reject) => {
      // setup files
      // try compile
      // if failed, reject with error + stdout,stderr
      // otherwise, resolve with parameters for runCode(param);
    });
  },
  testIntegration(opts) {
    return new Promise((resolve, reject) => {
    });
  },
});

// this will be provided by codewars-runner package
function createRunner(strategies) {
  return function(opts) {
    return new Promise((resolve, reject) => {
      // process options
      // do various setup
      // run
      // report
    });
  };
}

// usage
try {
  return runCode(await strategies[opts.strategy](opts));
} catch (err) { // compile error
  return fail(err);
}
// then report buffer
```

**Comment by jhoffner** [comment]
> How does strategies.files() work

I think the only use for this right now is in the javascript.js runner. It's a way to hook into the `opts.files` object and handle custom file processing such as transforming the files with babel. 

> How does customStrategy(opts)

I explained most of this in the other PR but the reason why assign is used is so that you can change more than just the custom run strategy, but also things like `files` and `sanitizeStdOut`. 

i.e. 

```javascript
module.exports = function(opts){
  return {
    custom: function(run, fail){
      run({name: 'node', args: ['-e', opts.solution]})
    },
   sanitizeStdOut: function(stdout) {
      return stdout.replace(/^warn:/g, '')
   }
  }
}
```

**Comment by jhoffner** [comment]
> These are blocking because I'm thinking of using the following:

I like it, I've always hated the shovel design but have just dealt with it all these years. The concept of the shovel shouldn't be needed to be known in order to add a new runner and you have achieve that here.

**Comment by kazk** [comment]
> I think the only use for this right now is in the javascript.js runner.

I missed that. In that usage, it should be possible to just turn `strategies.files()` into `strategies.files(opts)`.

---

> customStrategy can be taken out. The idea behind it is that when working with the new multi-file project format, you can also specify a customer runner. This could be useful for developing out new runners or for customizing the way one works for a specific challenge. It was an experiment.

> the reason why assign is used is so that you can change more than just the custom run strategy, but also things like `files` and `sanitizeStdOut`.

I'll take it out for now, but some ideas to implement this feature:

- For developing out new runners, I think `createRunner` can be reused somehow.
- For customizing the way one works for a specific challenge, I think doing `createRunner(Object.assign({}, baseStrategies, customStrategies))` will do? I think it's more simple to let it just override `solutionOnly` and/or `testIntegration` than defining the `custom` method.

Also, it sounds like this needs to be done much earlier because currently `setupFiles` is done before `customStrategy`, so changing `files` method has no effect.

**Comment by kazk** [comment]
@jhoffner What was the issue mentioned at the bottom of [lib/shovel.js](https://github.com/Codewars/codewars-runner-cli/blob/05b31129d1a27e656224f51c9ffc8fe24a504234/lib/shovel.js#L340)?
At first, I thought `line.normalize()` combining (default `'NFC'`) partial strings was the cause, but the comment has "large data".

```javascript
// we need to chunk the data back out to handle strange inconsistency issues with large data.
// Ideally we could chunk based off of character count but for some reason chunking by line breaks
// is the only thing that is consistent.
function writeToStream(stream, data, linebreak) {
  data.split(linebreak).forEach((line, i, arr) => {
    // don't write a line break on the last line
    return stream.write(line.normalize() + (i != arr.length - 1 ? linebreak : ''));
  });
}
```

Also, is there a reason for doing `line.normalize()`?

**Comment by jhoffner** [comment]
@kazk yeah I don't know nearly enough fundamentally about string encodings to have fixed this properly. Basically what was happening was that some kata that outputted various character sets would somehow cause the entire executable to change its encoding. Like, literally if you just sat there and watched the logs they would eventually switch to gibberish after a specific kata was ran and the encoding would never switch back without having to kill the program.  And by "gibberish", I wish I could tell you what actual encoding was but I'm not sure.

I didn't comment this code nearly enough. I remember adding `normalize` because it seemed like the thing to do and I think I was feeling desperate by that point, but I don't know that it actually fixed anything. breaking up the content into chunks was the major factor that fixed the issue.

**Comment by jhoffner** [comment]
BTW yes this only seemed to happen on large sets of output. Smaller sets of output using non-unicode characters acted fine. I have had a few battles with character encodings on this previously so the normalize may have came before I fixed the large text/chunking issue.

**Comment by kazk** [comment]
@jhoffner I think I found the possible cause. I still need to test it, but I'll write what I found so far.
Also, this might be related to Codewars/codewars.com#902?

> it might be coming back wrong from the CLI.

---

I think the root of this issue is how the output is streamed inside `exec`. I don't think it's handling multibyte characters properly and that's affecting any subsequent operations on them.

>  this only seemed to happen on large sets of output.

When the output is small enough to fit in single `chunk`, the following is enough because multibyte characters are in single `chunk`.

```javascript
child.stdout.on('data', function(chunk) {
  const text = chunk.toString('utf8'); // or chunk.toString();
});
```

When the output is large, there will be multiple `chunks` and multibyte characters can be split apart into separate `chunks`. The builtin [StringDecoder](https://nodejs.org/api/string_decoder.html) needs to be used to keep track of incomplete multibyte characters.

```javascript
const StringDecoder = require('string_decoder').StringDecoder;
const decoder = new StringDecoder('utf8');
child.stdout.on('data', function(chunk) {
  const text = decoder.write(chunk);
});
```

I'm not sure how `writeToStream` fixed this. Splitting at LF avoids splitting inside multibyte characters, but the concatenated string is already decoded incorrectly.

---

> Basically what was happening was that some kata that outputted various character sets would somehow cause the entire executable to change its encoding. Like, literally if you just sat there and watched the logs they would eventually switch to gibberish after a specific kata was ran and the encoding would never switch back without having to kill the program.

I just realized that I forgot about this point and I don't think I understand what you mean.
Can you clarify what "entire executable" is?

**Comment by kazk** [comment]
After reading some documentations, I think it's better to do `child.stdout.setEncoding('utf8');` in our case.

```javascript
child.stdout.setEncoding('utf8');
child.stdout.on('data', function(text) {
});
```

> The Readable stream will properly handle multi-byte characters delivered through the stream that would otherwise become improperly decoded if simply pulled from the stream as `Buffer` objects.
> <https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding>

---

This might also fix Codewars/codewars.com#902. I wasn't sure about why sometimes the same string outputs differently, but I forgot that streams are automatically adjusted. If the data is read from the stream slower, the chunk size will be smaller which explains the inconsistency.

**Comment by jhoffner** [comment]
Is #902 still happening? I had fixed that (or thought I did) via an issue that was caused by how the JSON result was being encoded into the Redis queue. This would explain why that issue was intermittent though.

**Comment by kazk** [comment]
I thought the issue wasn't resolved based on your last comment. I just tried outputting in Kumite and seems to be fixed :)

**Comment by kazk** [comment]
@jhoffner 

Some updates.

Made [examples folder (WIP)](https://github.com/kazk/codewars-runner/tree/08a7ee351ff90d10f0e147a24a5c3030e474f4ad/examples) showing how each runner might look like.

I'm looking for a way to *load* runner module instead of doing `createRunner(strategies)` to define a module. So only the following will be needed.

```javascript
export async function solutionOnly(opts) {
}

export async function testIntegration(opts) {
}
```

See [tests](https://github.com/kazk/codewars-runner/tree/08a7ee351ff90d10f0e147a24a5c3030e474f4ad/test) for the current state.

---

[Docker 17.05](https://github.com/moby/moby/releases/tag/v17.05.0-ce) adds [multistage-build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) and it's worth looking into.

---

I have few questions before you leave, I'll comment them separately.

**Comment by kazk** [comment]
@jhoffner 

In #404 you wrote:

> In production we pre-warm containers before making them available by running `listen.js`, then connect to the container and use docker exec to run the actual `run-json.js` file, so everything should be warm by then.
>
> Our scheduling engine will use `docker exec` on a pre-started instance and then kill the instance after it is done, then wait till the next instance is started before taking on any more work for that node (cluster node, not node JS)

I imagined something like the following:

```
POST /run

internal
run-ruby
- ruby-runner1 (docker exec)
- ruby-runner2 (ready; running)
- ruby-runner3 (starting)

run-ruby
- ruby-runner2 (docker exec)
- ruby-runner3 (ready; running)
- ruby-runner1 (killed; restarting)
```

Is this close to what you meant?

Is it possible for you to let me know more details? I'd like to make things more flexible, but I need to know the intended usage and/or requirements. I think I read somewhere it's on AWS ECS?

**Comment by jhoffner** [comment]
```
export async function solutionOnly(opts) {
}

export async function testIntegration(opts) {
}
```

Can Node support ES6 modules now? I can't even keep up with this stuff anymore. Thats awesome if it does.

> I imagined something like the following:...

Yes, except that its actually more like:
```
- ruby-runner (docker exec)
- node-runner (ready)
- python-runner (ready)
...
```

So one instance of each type of runner. We prewarm them all and when all are ready we start taking jobs. We make sure to not do anything else on the machine while a runner is running to try to prevent resource contention, which is why you would never see (running) and (restarting) at the same time across runners.  

>  multistage-build

Another cool feature that I didn't know about.

**Comment by kazk** [comment]
> Can Node support ES6 modules now?

No :( I just used it because it expressed my intention better.
[rollup](https://rollupjs.org/) with `npm`'s `prepublish` hook allows us to write it this way and publish in CommonJS style automatically, if we want. It seems like new extension (`.mjs`) will be introduced to support ES modules. <http://2ality.com/2017/05/es-module-specifiers.html>

---

So there're multiple clusters like that?

Is this correct interpretation of the life cycle?
```
- ruby-runner (ready)
- node-runner (ready)
- python-runner (ready)

---

- ruby-runner (docker exec)
- node-runner (ready)
- python-runner (ready)

---

- ruby-runner (finished; killed)
- node-runner (ready)
- python-runner (ready)

---

- ruby-runner (ready)
- node-runner (ready)
- python-runner (ready)
```

> you would never see (running) and (restarting) at the same time across runners.

So it waits until `ruby-runner` becomes ready in the above example? and not take non-ruby-runner jobs?

What are you using to manage these jobs?

I thought you had a cluster per runner because it seemed easier to manage and costs less by scaling by need. (e.g., node-runner gets more containers than some of less popular ones)

**Comment by kazk** [comment]
I think I misunderstood.
"scaling by need" can't happen because only one container can be running at a time.
So increasing the amount of "ready" containers won't be an improvement.
The following is not an option because the resource is shared.

```
- ruby-runner1 (docker exec)
- ruby-runner2 (docker exec)
- ruby-runner3 (ready)
- ruby-runner4 (starting)
```

**Comment by jhoffner** [comment]
It's a fleet of servers with each server running one instance of each runner. Only one runner runs at a time. The next job will not be pulled until the previous runner has been replaced. There is no concept of runner specific queues. 

So effectively each server can only handle one job at a time, which is why we run many cheap servers. Unfortunate running on cheaper servers (AWS T2.micro) is likely the reason why code sometimes timesout, even though the server is only handling one job at a time, since creating containers and starting these short lived programs/runs cause a large CPU spike. 

While we will keep the ephemeral one time use architecture around regardless, my next big goal with the scheduler is to also support persistent containers that stay with you through the entire life of taking a challenge/kata. Main reasons for doing so will be to provide repl support and the ability to customize each container with a startup bash script that would allow Sudo access for installation. 

Then beyond that is the ability to save container states as new images so that they can be consistently loaded.
